proxy-groups:
  - name: èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - æ‰‹åŠ¨é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/vmssrNotice.png
  - name: æ‰‹åŠ¨é€‰æ‹©
    type: select
    include-all: true
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/rocket(1).png
  - name: å·´å“ˆå§†ç‰¹
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - èŠ‚ç‚¹é€‰æ‹©
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/bahamute.png
  - name: å£°ç”°éŸ³ä¹
    type: select
    proxies:
      - å°æ¹¾èŠ‚ç‚¹
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/spotify(green).png
  - name: äººå·¥æ™ºèƒ½
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/chatgpt(white).png
  - name: æ¸¸æˆå¹³å°
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/game.png
  - name: å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/quanqiu(1).png
  - name: è‹¹æœè´¦æˆ·
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/apple(1).png
  - name: è‹¹æœå•†åº—
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/AppStore(1).png
  - name: è‹¹æœæµ‹è¯•
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - REJECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/testflight(1).png
  - name: å…œåº•åˆ†æµ
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - DIRECT
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/nyamedia-emby.png
  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|HKG|Hong)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/Hongkong.png
  - name: å°æ¹¾èŠ‚ç‚¹
    type: url-test
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡¹ğŸ‡¼|å°æ¹¾|(\b(TW|TWN|Tai|Taiwan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/taiwan(3).png
  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|JPN|Japan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/zl-icon-jp-flag.png
  - name: ç‹®åŸèŠ‚ç‚¹
    type: url-test
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|SGP|Singapore)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/singapore(1).png
  - name: ç¾å›½èŠ‚ç‚¹
    type: url-test 
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|USA|United States)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/US.png
  - name: å¾·å›½èŠ‚ç‚¹
    type: url-test
    include-all: true
    filter: '^(?=.*((?i)ğŸ‡©ğŸ‡ª|å¾·å›½|(\b(DE|DEU|Germany)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    interval: 600
    tolerance: 50
    icon: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Icons/Germany(1).png

rule-providers:
  Liqiye_Direct:
    url: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Rule/Direct.txt
    path: ./ruleset/Liqiye_Direct.yaml
    behavior: classical
    interval: 3600
    format: text
    type: http
  Liqiye_GFW:
    url: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Rule/GFW.txt
    path: ./ruleset/Liqiye_GFW.yaml
    behavior: classical
    interval: 3600
    format: text
    type: http
  Liqiye_Block:
    url: https://raw.githubusercontent.com/FaithAluten/Profile/refs/heads/main/Rule/Block.txt
    path: ./ruleset/Liqiye_Block.yaml
    behavior: classical
    interval: 3600
    format: text
    type: http
  sogouinput:
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/sogouinput.txt
    behavior: classical
    interval: 3600
    format: text
    type: http
  Lan:
    url: https://kelee.one/Tool/Clash/Rule/LAN_SPLITTER.yaml
    path: ./ruleset/Lan.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  Direct:
    url: https://kelee.one/Tool/Clash/Rule/Direct.yaml
    path: ./ruleset/Direct.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  Proxy:
    url: https://kelee.one/Tool/Clash/Rule/Proxy.yaml
    path: ./ruleset/Proxy.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  ChinaDownloadCDN:
    url: https://kelee.one/Tool/Clash/Rule/ChinaDownloadCDN.yaml
    path: ./ruleset/ChinaDownloadCDN.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  InternationalDownloadCDN:
    url: https://kelee.one/Tool/Clash/Rule/InternationalDownloadCDN.yaml
    path: ./ruleset/InternationalDownloadCDN.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  Bahamut:
    url: https://rule.kelee.one/Clash/Bahamut.yaml
    path: ./ruleset/Bahamut.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http  
  Spotify:
    url: https://rule.kelee.one/Clash/Spotify.yaml
    path: ./ruleset/Spotify.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  AI:
    url: https://kelee.one/Tool/Clash/Rule/AI.yaml
    path: ./ruleset/AI.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  Steam:
    url: https://rule.kelee.one/Clash/Steam.yaml
    path: ./ruleset/Steam.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  Game:
    url: https://kelee.one/Tool/Clash/Rule/Game.yaml
    path: ./ruleset/Game.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  iCloudChina:
    url: https://kelee.one/Tool/Clash/Rule/iCloudChina.yaml
    path: ./ruleset/iCloudChina.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  ApplePushNotificationService:
    url: https://kelee.one/Tool/Clash/Rule/ApplePushNotificationService.yaml
    path: ./ruleset/ApplePushNotificationService.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  AppleSoftwareUpdates:
    url: https://kelee.one/Tool/Clash/Rule/AppleSoftwareUpdates.yaml
    path: ./ruleset/AppleSoftwareUpdates.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  AppleID:
    url: https://kelee.one/Tool/Clash/Rule/AppleAccount.yaml
    path: ./ruleset/AppleID.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  AppStore:
    url: https://kelee.one/Tool/Clash/Rule/AppStore.yaml
    path: ./ruleset/AppStore.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  TestFlight:
    url: https://rule.kelee.one/Clash/TestFlight.yaml
    path: ./ruleset/TestFlight.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http
  ESET_China:
    url: https://kelee.one/Tool/Clash/Rule/ESET_China.yaml
    path: ./ruleset/ESET_China.yaml
    behavior: classical
    interval: 3600
    format: yaml
    type: http

rules:
  - RULE-SET,Liqiye_Direct,DIRECT
  - RULE-SET,Liqiye_GFW,å…¨çƒåŠ é€Ÿ
  - RULE-SET,Liqiye_Block,REJECT
  - RULE-SET,sogouinput,REJECT
  - RULE-SET,Lan,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Proxy,å…¨çƒåŠ é€Ÿ
  - RULE-SET,ChinaDownloadCDN,DIRECT
  - RULE-SET,InternationalDownloadCDN,å…¨çƒåŠ é€Ÿ
  - RULE-SET,Bahamut,å·´å“ˆå§†ç‰¹
  - RULE-SET,Spotify,å£°ç”°éŸ³ä¹
  - RULE-SET,AI,äººå·¥æ™ºèƒ½
  - RULE-SET,Steam,å…¨çƒåŠ é€Ÿ
  - RULE-SET,Game,æ¸¸æˆå¹³å°
  - RULE-SET,iCloudChina,DIRECT
  - RULE-SET,ApplePushNotificationService,DIRECT
  - RULE-SET,AppleSoftwareUpdates,DIRECT
  - RULE-SET,AppleID,è‹¹æœè´¦æˆ·
  - RULE-SET,AppStore,è‹¹æœå•†åº—
  - RULE-SET,TestFlight,è‹¹æœæµ‹è¯•
  - RULE-SET,ESET_China,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,å…œåº•åˆ†æµ
